<?php

namespace Database\Factories\Cms;

use App\Models\User;
use App\Services\Cms\Models\ContentItem;
use App\Services\Platform\Models\Tenant;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Services\Cms\Models\ContentItem>
 */
class ContentItemFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = ContentItem::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $title = fake()->sentence(6, true);
        $type = fake()->randomElement(['post', 'page', 'project']);

        return [
            'tenant_id' => Tenant::factory(),
            'author_id' => User::factory(),
            'type' => $type,
            'title' => rtrim($title, '.'),
            'slug' => '', // Will be auto-generated by model
            'excerpt' => fake()->paragraph(2),
            'body' => $this->generateMarkdownContent(),
            'status' => 'draft',
            'published_at' => null,
            'meta' => [
                'featured_image' => fake()->imageUrl(1200, 630),
                'seo_title' => fake()->sentence(8),
                'seo_description' => fake()->paragraph(1),
            ],
        ];
    }

    /**
     * Generate realistic markdown content.
     */
    protected function generateMarkdownContent(): string
    {
        $content = "# " . fake()->sentence(4) . "\n\n";
        $content .= fake()->paragraph(4) . "\n\n";
        $content .= "## " . fake()->sentence(3) . "\n\n";
        $content .= fake()->paragraph(5) . "\n\n";
        $content .= "- " . fake()->sentence() . "\n";
        $content .= "- " . fake()->sentence() . "\n";
        $content .= "- " . fake()->sentence() . "\n\n";
        $content .= fake()->paragraph(3) . "\n\n";
        $content .= "## " . fake()->sentence(3) . "\n\n";
        $content .= fake()->paragraph(6) . "\n\n";
        $content .= "> " . fake()->sentence(10) . "\n\n";
        $content .= fake()->paragraph(4);

        return $content;
    }

    /**
     * Create a published content item.
     */
    public function published(): static
    {
        return $this->state(fn(array $attributes) => [
            'status' => 'published',
            'published_at' => fake()->dateTimeBetween('-6 months', 'now'),
        ]);
    }

    /**
     * Create an archived content item.
     */
    public function archived(): static
    {
        return $this->state(fn(array $attributes) => [
            'status' => 'archived',
            'published_at' => fake()->dateTimeBetween('-2 years', '-6 months'),
        ]);
    }

    /**
     * Create a draft content item.
     */
    public function draft(): static
    {
        return $this->state(fn(array $attributes) => [
            'status' => 'draft',
            'published_at' => null,
        ]);
    }

    /**
     * Create a post type content item.
     */
    public function post(): static
    {
        return $this->state(fn(array $attributes) => [
            'type' => 'post',
        ]);
    }

    /**
     * Create a page type content item.
     */
    public function page(): static
    {
        return $this->state(fn(array $attributes) => [
            'type' => 'page',
            'excerpt' => null, // Pages typically don't have excerpts
        ]);
    }

    /**
     * Create a project type content item.
     */
    public function project(): static
    {
        $technologies = ['Laravel', 'Vue.js', 'React', 'Node.js', 'Python', 'Docker'];

        return $this->state(fn(array $attributes) => [
            'type' => 'project',
            'meta' => [
                'featured_image' => fake()->imageUrl(1200, 630),
                'project_url' => fake()->url(),
                'github_url' => 'https://github.com/' . fake()->userName() . '/' . fake()->slug(2),
                'technologies' => fake()->randomElements($technologies, fake()->numberBetween(2, 4)),
                'completion_date' => fake()->date(),
            ],
        ]);
    }

    /**
     * Create content for a specific tenant.
     */
    public function forTenant(Tenant $tenant): static
    {
        return $this->state(fn(array $attributes) => [
            'tenant_id' => $tenant->id,
        ]);
    }

    /**
     * Create content by a specific author.
     */
    public function byAuthor(User $user): static
    {
        return $this->state(fn(array $attributes) => [
            'author_id' => $user->id,
        ]);
    }
}
