<?php

namespace Database\Factories\Cms;

use App\Services\Cms\Models\Tag;
use App\Services\Platform\Models\Tenant;
use Illuminate\Database\Eloquent\Factories\Factory;

/**
 * @extends \Illuminate\Database\Eloquent\Factories\Factory<\App\Services\Cms\Models\Tag>
 */
class TagFactory extends Factory
{
    /**
     * The name of the factory's corresponding model.
     *
     * @var string
     */
    protected $model = Tag::class;

    /**
     * Define the model's default state.
     *
     * @return array<string, mixed>
     */
    public function definition(): array
    {
        $tags = [
            'Laravel',
            'PHP',
            'JavaScript',
            'Vue.js',
            'React',
            'Node.js',
            'Python',
            'Django',
            'Docker',
            'Kubernetes',
            'DevOps',
            'CI/CD',
            'Testing',
            'TDD',
            'API',
            'REST',
            'GraphQL',
            'Database',
            'MySQL',
            'PostgreSQL',
            'MongoDB',
            'Redis',
            'AWS',
            'Azure',
            'Tutorial',
            'Guide',
            'Tips',
            'Best Practices',
            'Security',
            'Performance',
            'Optimization',
            'Architecture',
            'Design Patterns'
        ];

        $name = fake()->unique()->randomElement($tags);

        return [
            'tenant_id' => Tenant::factory(),
            'name' => $name,
            'slug' => '', // Will be auto-generated by model
        ];
    }

    /**
     * Create a tag for a specific tenant.
     */
    public function forTenant(Tenant $tenant): static
    {
        return $this->state(fn(array $attributes) => [
            'tenant_id' => $tenant->id,
        ]);
    }

    /**
     * Create a programming language tag.
     */
    public function programmingLanguage(): static
    {
        $languages = ['PHP', 'JavaScript', 'Python', 'Ruby', 'Java', 'Go', 'Rust', 'TypeScript'];

        return $this->state(fn(array $attributes) => [
            'name' => fake()->randomElement($languages),
        ]);
    }

    /**
     * Create a framework tag.
     */
    public function framework(): static
    {
        $frameworks = ['Laravel', 'Vue.js', 'React', 'Angular', 'Django', 'Flask', 'Express', 'Next.js'];

        return $this->state(fn(array $attributes) => [
            'name' => fake()->randomElement($frameworks),
        ]);
    }

    /**
     * Create a category tag.
     */
    public function category(): static
    {
        $categories = ['Tutorial', 'Guide', 'News', 'Review', 'Opinion', 'Case Study', 'Interview'];

        return $this->state(fn(array $attributes) => [
            'name' => fake()->randomElement($categories),
        ]);
    }
}
